hardware_interface:
  joints:
    - base_joint_planar
    - wheel_left_joint
    - wheel_right_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: WafflePi_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_joint_planar
      - wheel_left_joint
      - wheel_right_joint
