controller_list:
  - name: fake_WafflePi_controller
    type: $(arg fake_execution_type)
    joints:
      - base_joint_planar
      - wheel_left_joint
      - wheel_right_joint
initial:  # Define initial robot poses per group
#  - group: WafflePi
#    pose: home

  []