WafflePi_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
  #  - base_joint
    - wheel_left_joint
    - wheel_right_joint
  gains:
    base_joint_planar:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wheel_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wheel_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1